## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy as np
print(np.linspace (-1.3, 2.5, 65))

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [20]:
n = int(input())
a = np.array([1, 2, 3] * n)
print(a)

3
[1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [21]:
import numpy as np
a = 10
print(np.arange(1, a*2, 2))

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [24]:
import numpy as np
a = np.zeros((10, 10), dtype=int)
a[0, :] = 1
a[9, :] = 1
a[:, 0] = 1
a[:, 9] = 1
print(a)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [17]:
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [2]:
import numpy as np
def matrix(n):
    rows_index = np.arange(n)
    cols_index = np.arange(n)
    return rows_index[:, np.newaxis] + cols_index
print(matrix(7))

[[ 0  1  2  3  4  5  6]
 [ 1  2  3  4  5  6  7]
 [ 2  3  4  5  6  7  8]
 [ 3  4  5  6  7  8  9]
 [ 4  5  6  7  8  9 10]
 [ 5  6  7  8  9 10 11]
 [ 6  7  8  9 10 11 12]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [1]:
import numpy as np
vector1 = np.random.randint(5, size = 4)
vector2 = np.random.randint(5, size = 4)
matrix1 = np.random.randint(5, size = (3,4))
matrix2 = np.random.randint(5, size = (4,3))

vectors_multiplication = np.dot(vector1, vector2)
matrix_vector_multiplication = np.dot(matrix1, vector1)
matrixes_multiplication = np.dot(matrix1, matrix2)

print(vectors_multiplication)
print(matrix_vector_multiplication)
print(matrixes_multiplication)

11
[19 15  7]
[[18 15 33]
 [ 9 10 25]
 [ 9  8 20]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [17]:
import numpy as np
x = np.arange(0, 1.05, 0.05)
cos_x = np.cos(x)
sin_x = np.sin(x)
result = np.column_stack((cos_x, sin_x)).astype(str)
print(result)

[['1.0' '0.0']
 ['0.9987502603949663' '0.04997916927067833']
 ['0.9950041652780258' '0.09983341664682815']
 ['0.9887710779360422' '0.14943813247359924']
 ['0.9800665778412416' '0.19866933079506122']
 ['0.9689124217106447' '0.24740395925452294']
 ['0.955336489125606' '0.2955202066613396']
 ['0.9393727128473789' '0.3428978074554514']
 ['0.9210609940028851' '0.3894183423086505']
 ['0.9004471023526769' '0.43496553411123023']
 ['0.8775825618903728' '0.479425538604203']
 ['0.8525245220595057' '0.5226872289306592']
 ['0.8253356149096782' '0.5646424733950355']
 ['0.7960837985490559' '0.6051864057360395']
 ['0.7648421872844884' '0.6442176872376911']
 ['0.7316888688738209' '0.6816387600233341']
 ['0.6967067093471654' '0.7173560908995228']
 ['0.6599831458849821' '0.7512804051402927']
 ['0.6216099682706644' '0.7833269096274834']
 ['0.5816830894638835' '0.8134155047893737']
 ['0.5403023058681398' '0.8414709848078965']]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [3]:
a, b = -1, 3
A = (b - a) * np.random.rand(3, 5) + a
print(A)

[[-0.95615261  2.38125433  1.19354668  1.95447965 -0.71077543]
 [-0.62912965 -0.72256967  1.53425544 -0.88403989  1.34608588]
 [ 2.85421368  2.51220907  2.94148642  2.34217896  0.50012171]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [4]:
import numpy as np
sum_elements = np.sum(A)
sum_rows = np.sum(A, axis = 1)
sum_cols = np.sum(A, axis = 0)
mean_rows = np.mean(A, axis = 1)
var_rows = np.var(A, axis = 1)
std_rows = np.std(A, axis = 1)
print(sum_elements)
print(sum_rows)
print(sum_cols)
print(mean_rows)
print(var_rows)
print(std_rows)

15.657164574965726
[ 3.86235262  0.64460211 11.15020984]
[1.26893142 4.17089373 5.66928854 3.41261872 1.13543216]
[0.77247052 0.12892042 2.23004197]
[1.87015851 1.15644443 0.79611212]
[1.36753739 1.07538106 0.89225115]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [5]:
import numpy as np
A = (A - mean_rows[:, np.newaxis]) / std_rows[:, np.newaxis]
print(A)

[[-1.26404086  1.17640938  0.30790833  0.86433405 -1.0846109 ]
 [-0.70491298 -0.79180313  1.30682515 -0.94195476  1.13184573]
 [ 0.6995471   0.31624179  0.79735896  0.12567873 -1.93882658]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [6]:
import numpy as np
sort_index = np.argsort(A[:, 2])
A_sorted = A[sort_index]
print(A_sorted)

[[-1.26404086  1.17640938  0.30790833  0.86433405 -1.0846109 ]
 [ 0.6995471   0.31624179  0.79735896  0.12567873 -1.93882658]
 [-0.70491298 -0.79180313  1.30682515 -0.94195476  1.13184573]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [7]:
import numpy as np
B = np.dot(A.T, A)
C = np.dot(A, A.T)
print('B = ', B)
print('C = ', C)

B =  [[ 2.58406775 -0.70765119 -0.75261657 -0.34063923 -0.78316077]
 [-0.70765119  2.1109001  -0.42036377  1.80239828 -2.78528342]
 [-0.75261657 -0.42036377  2.43838083 -0.86462346 -0.40077703]
 [-0.34063923  1.80239828 -0.86462346  1.65014726 -2.24728286]
 [-0.78316077 -2.78528342 -0.40077703 -2.24728286  6.21650407]]
C =  [[ 5.         -1.67983926  1.944788  ]
 [-1.67983926  5.         -2.01434859]
 [ 1.944788   -2.01434859  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [8]:
import numpy as np
sum_B = np.trace(B)
sum_C = np.trace(C)
print(sum_B)
print(sum_C)

15.0
15.0


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [13]:
import numpy as np
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
rank_C = np.linalg.matrix_rank(C)
eigvalsh_B = np.linalg.eigvalsh(B)
eigvalsh_C = np.linalg.eigvalsh(C)
print(det_B)
print(det_C)

-3.593293039181767e-30
84.85317399858589


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [15]:
import numpy as np
np.random.seed(1032201390)
np.random.randint(9)

4